cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://williamsantana-portfolio.vercel.app

file:
  upload-dir: /upload

security:
  jwt:
    token:
      secret-key: 53cr57
      expire-length: 3600000

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimeZone=true&serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
    # spring.jpa.open-in-view
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    net.sf.japerreports: DEBUG
    com.jaspersoft: DEBUG
    br.com.WorkingWithJasperReports: DEBUG

spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    user-root-path: true